const $=id=>document.getElementById(id);
const DB_NAME='street-atlas-db', STORE='entries';let db, photoData='', selectedType='猫咪', selectedMood='慵懒', currentId=null;
const descriptions={猫咪:['摸到一颗软乎乎的毛球。','它蹭了蹭手，今天就变得柔软起来。','短暂贴贴，是今天的小治愈。'],狗狗:['摸到一位热情的小伙伴。','摇尾巴的瞬间，快乐也跟着摇起来。','今天收获了一次温柔贴贴。'],其他小动物:['今天的街头，又多了一位可爱邻居。'],其他:['今天的街头，又多了一位可爱邻居。','世界很大，今天又认识了一小部分。','谢谢你，让平常的一天多了个小惊喜。']};
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id',autoIncrement:true});r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function all(){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.id-a.id));r.onerror=()=>rej(r.error)})}
function put(v){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).add(v);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function remove(id){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0)}
function dateText(d){return new Date(d).toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).replaceAll('/','.')}
function desc(type){const a=descriptions[type]||descriptions.其他;return a[Math.floor(Math.random()*a.length)]}
function cardHTML(e){return `<div class="collection-card"><div class="card-inner"><div class="card-top"><span>✳ STREET PET DIARY</span><span class="card-seal">✿</span></div><img class="card-photo" src="${e.photo}" alt="收录的动物照片"><h2 class="card-name">${escapeHTML(e.name||'无名小友')}</h2><div class="card-latin">A SOFT LITTLE MOMENT</div><div class="card-tags"><span class="tag">${e.type}</span><span class="tag">${e.mood}</span></div><p class="card-desc">${escapeHTML(e.description)}</p><div class="card-meta"><span>${escapeHTML(e.place||'街头偶遇')} · ${dateText(e.date)}</span><span class="card-number">NO.${String(e.id).padStart(3,'0')}</span></div></div></div>`}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function refresh(){const entries=await all();$('count').textContent=entries.length;$('atlasCount').textContent=entries.length;$('recent').innerHTML=entries.length?entries.slice(0,4).map(e=>`<button class="atlas-item" data-open="${e.id}"><img src="${e.photo}"><strong>${escapeHTML(e.name||'无名小友')}</strong><small>NO.${String(e.id).padStart(3,'0')} · ${e.type}</small></button>`).join(''):'<div class="empty-mini"><span>☘</span><p>你的第一位街头朋友，<br>正在等你遇见。</p></div>';$('atlasGrid').innerHTML=entries.length?entries.map(e=>`<button class="atlas-item" data-open="${e.id}"><img src="${e.photo}"><strong>${escapeHTML(e.name||'无名小友')}</strong><small>NO.${String(e.id).padStart(3,'0')} · ${e.type}</small></button>`).join(''):'<div class="empty-atlas">还没有收藏。<br>下一次街头相遇，就从这里开始吧。<br><br><button class="primary" id="emptyAdd">＋ 收录新朋友</button></div>'}
function begin(){photoData='';$('photoInput').value='';$('photoPreview').hidden=true;$('photoPlaceholder').hidden=false;$('changePhoto').hidden=true;$('petName').value='';$('place').value='';$('diary').value='';selectedType='猫咪';selectedMood='慵懒';document.querySelectorAll('#typeChoices .choice').forEach(b=>b.classList.toggle('selected',b.dataset.value===selectedType));document.querySelectorAll('#moodChoices .choice').forEach(b=>b.classList.toggle('selected',b.dataset.value===selectedMood));$('nextNo').textContent=String((Number($('count').textContent)||0)+1).padStart(3,'0');show('form')}
$('addFromHome').onclick=begin;$('photoPicker').onclick=()=>$('photoInput').click();$('changePhoto').onclick=e=>{e.stopPropagation();$('photoInput').click()};
$('photoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/'))return alert('请选择图片文件');const reader=new FileReader();reader.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext('2d').drawImage(im,0,0);photoData=reader.result;$('photoPreview').src=photoData;$('photoPreview').hidden=false;$('photoPlaceholder').hidden=true;$('changePhoto').hidden=false};im.src=reader.result};reader.readAsDataURL(f)};
document.querySelectorAll('#typeChoices .choice').forEach(b=>b.onclick=()=>{selectedType=b.dataset.value;document.querySelectorAll('#typeChoices .choice').forEach(x=>x.classList.toggle('selected',x===b))});
document.querySelectorAll('#moodChoices .choice').forEach(b=>b.onclick=()=>{selectedMood=b.dataset.value;document.querySelectorAll('#moodChoices .choice').forEach(x=>x.classList.toggle('selected',x===b))});
$('saveEncounter').onclick=async()=>{if(!photoData)return alert('先添加刚刚拍下的小家伙照片吧！');const e={photo:photoData,name:$('petName').value.trim(),type:selectedType,mood:selectedMood,place:$('place').value.trim(),diary:$('diary').value.trim(),date:new Date().toISOString(),description:desc(selectedType)};try{e.id=await put(e);currentId=e.id;$('cardMount').innerHTML=cardHTML(e);await refresh();await playCaptureAnimation(e.photo);show('cardScreen')}catch(err){alert('保存失败，可能是浏览器空间不足。请尝试缩小照片后再试。')}};

function playCaptureAnimation(photo){return new Promise(resolve=>{const overlay=document.createElement('div');overlay.className='capture-overlay';overlay.innerHTML=`<div class="capture-stage"><span class="capture-spark one">✦</span><span class="capture-spark two">✧</span><span class="capture-spark three">✿</span><div class="capture-ball"><i class="ball-shine"></i></div><div class="capture-caption">正在把这次相遇收进图鉴…</div></div>`;document.body.appendChild(overlay);setTimeout(()=>overlay.classList.add('captured'),650);setTimeout(()=>overlay.classList.add('opened'),1550);setTimeout(()=>{overlay.remove();resolve()},2200)})}
async function showAtlas(){await refresh();show('atlas')}$('allBtn').onclick=showAtlas;$('toAtlas').onclick=showAtlas;
async function openDetail(id){const e=(await all()).find(x=>x.id===Number(id));if(!e)return;currentId=e.id;$('detailMount').innerHTML=`<div class="page-title"><span class="eyebrow">NO.${String(e.id).padStart(3,'0')} · YOUR FRIEND</span><h1>${escapeHTML(e.name||'无名小友')}</h1></div><div class="card-mount detail-card">${cardHTML(e)}</div><button class="primary big" id="detailDownload">↓ 保存图鉴卡</button><button class="delete-btn" id="deleteEntry">删除这条记录</button>`;$('detailDownload').onclick=()=>download(e);$('deleteEntry').onclick=async()=>{if(confirm('确定要从图鉴中删除这位朋友吗？')){await remove(e.id);await showAtlas()}};show('detail')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openDetail(b.dataset.open);if(e.target.id==='emptyAdd')begin()});
function download(e){const img=new Image();img.onload=()=>{const margin=80,photoW=img.naturalWidth,photoH=img.naturalHeight,canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=photoW+margin*2;canvas.height=photoH+610;const W=canvas.width,H=canvas.height;ctx.fillStyle='#fffaf0';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#d7d1bf';ctx.lineWidth=3;ctx.strokeRect(28,28,W-56,H-56);ctx.strokeRect(48,48,W-96,H-96);ctx.fillStyle='#65785c';ctx.font='bold 25px sans-serif';ctx.fillText('✳  STREET PET DIARY',margin,105);ctx.beginPath();ctx.arc(W-110,95,35,0,Math.PI*2);ctx.stroke();ctx.font='32px sans-serif';ctx.fillText('✿',W-127,107);const x=margin,y=150;ctx.fillStyle='#f0eadb';ctx.fillRect(x-8,y-8,photoW+16,photoH+16);ctx.drawImage(img,x,y,photoW,photoH);let textY=y+photoH+85;ctx.fillStyle='#303b30';ctx.font='bold 56px sans-serif';ctx.fillText((e.name||'无名小友').slice(0,12),margin,textY);textY+=55;ctx.fillStyle='#65785c';ctx.font='28px sans-serif';ctx.fillText('A SOFT LITTLE MOMENT',margin,textY);textY+=35;ctx.fillStyle='#e9eddf';roundRect(ctx,margin,textY,145,48,20);ctx.fill();roundRect(ctx,margin+160,textY,145,48,20);ctx.fill();ctx.fillStyle='#56684e';ctx.font='23px sans-serif';ctx.fillText(e.type,margin+23,textY+32);ctx.fillText(e.mood,margin+183,textY+32);textY+=85;ctx.fillStyle='#6f7465';ctx.font='25px sans-serif';wrapText(ctx,e.description,margin,textY,photoW,38);ctx.strokeStyle='#e0dccf';ctx.beginPath();ctx.moveTo(margin,textY+65);ctx.lineTo(W-margin,textY+65);ctx.stroke();ctx.fillStyle='#8a8b7c';ctx.font='20px sans-serif';ctx.fillText(`${e.place||'街头偶遇'} · ${dateText(e.date)}`,margin,textY+105);ctx.fillStyle='#65785c';ctx.font='26px Georgia';ctx.textAlign='right';ctx.fillText(`NO.${String(e.id).padStart(3,'0')}`,W-margin,textY+105);canvas.toBlob(blob=>{if(!blob){alert('图片尺寸超出当前浏览器可导出的范围，请尝试使用原图较小的版本。');return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`街头撸宠手账-NO${String(e.id).padStart(3,'0')}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')};img.onerror=()=>alert('图片读取失败，请重新上传照片');img.src=e.photo}
function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}function wrapText(c,s,x,y,max,lh){let line='';for(const ch of s){if(c.measureText(line+ch).width>max){c.fillText(line,x,y);line=ch;y+=lh}else line+=ch}c.fillText(line,x,y)}
$('downloadCard').onclick=async()=>{const e=(await all()).find(x=>x.id===currentId);if(e)download(e)};$('aboutBtn').onclick=()=>$('aboutModal').classList.add('show');$('closeAbout').onclick=$('gotIt').onclick=()=>$('aboutModal').classList.remove('show');
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));
$('dateToday').textContent=new Date().toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'}).replace('/','.') ;
openDB().then(refresh).catch(()=>alert('当前浏览器不支持本地图鉴存储，请使用较新的 Chrome、Safari 或 Edge。'));
